### ISSUE TITLE
Error while running make on manjaro: Error 127

### ISSUE THREAD

**Issue by narendra-manchala** [begriffs/pg_rational#21]
Postgres Verion: 12.2

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=20.0
DISTRIB_CODENAME=Lysia
DISTRIB_DESCRIPTION="Manjaro Linux"

While running `make` i got the following error
`/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -std=c99 -Wextra -Wpedantic -I. -I./ -I/usr/include/postgresql/server -I/usr/include/postgresql/internal  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o pg_rational.bc pg_rational.c
make: /usr/bin/clang: No such file or directory
make: *** [/usr/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:1044: pg_rational.bc] Error 127
`

**Comment by begriffs** [comment]
Sorry, I only now noticed your issue!

Do you perhaps have more than one postgresql version installed on the system? What does `which pg_config` show? The Makefile uses pg_config to add its make targets:
https://github.com/begriffs/pg_rational/blob/master/Makefile#L7-L9

**Comment by begriffs** [comment]
@narendra-manchala did you resolve this?
