### ISSUE TITLE
Put a link to your blog post in the README?

### ISSUE THREAD

**Issue by ctsrc** [begriffs/pg_rational#4]
The blog post you wrote about this was great and explained the extension and your motivation for creating it and how to use it in an excellent manner.

I suggest adding a link to said blog post at the very top of the README.

https://begriffs.com/posts/2018-03-20-user-defined-order.html

**Comment by begriffs** [comment]
Great suggestion, I'll do that.

**Comment by begriffs** [comment]
Done!
