### ISSUE TITLE
pg_rational.control claims support for 'bigint fractions'

### ISSUE THREAD

**Issue by df7cb** [begriffs/pg_rational#8]
The extension's comment in pg_rational.control claims support for 'bigint fractions' - it should be 'int', I'd think.

PS: A simple version tag is all I'd need to finish the Debian packaging, so I can pull a tarball from github. Thanks!

**Comment by begriffs** [comment]
Does it still make that claim? When I first designed the extension I used bigint sizes for numerators and denominators, but have since switched them to ints.

Also I have added a v0.0.1 tag, does that work for you?

**Comment by df7cb** [comment]
Hi,
it's still mentioned in the control file: `pg_rational.control:comment = 'bigint fractions'` which will show up as description in the `\dx` output.

Thanks for the tag, the packages for Debian and apt.postgresql.org are on their way!
